export const DEBIT_CARD = [
  "EasyShop Imperia Platinum Chip Debit Card",
  "EasyShop Preferred Platinum Debit Card",
  "Easyshop Classic Platinum Debit Card",
  "EasyShop Platinum",
  "Times Points Debit Card",
  "Rewards Debit Card",
  "EasyShop self_employed",
  "Rupay Premium",
  "EasyShop Rupay NRO Debit Card",
  "Emirates BankBuddy Bank Signature Debit Card",
  "EasyShop",
  "EasyShop Woman's Advantage",
  "EasyShop Titanium Royale",
  "EasyShop Titanium",
  "EasyShop NRO",
  "EasyShop Gold",
  "Emirates BankBuddy Bank World Debit Card",
  "Millennia Debit Card",
];
